/spot_manipulator_teleop_cartesian:
  ros__parameters:
    enable_button: 5
    axis_linear:
      x: 1
      y: 0
      z: 3
    scale_linear:
      x: 0.1
      y: 0.1
      z: 0.1

/spot_manipulator_teleop_angular:
  ros__parameters:
    enable_button: 7
    axis_angular:
      roll: 2
      pitch: 1
      yaw: 0
    scale_angular:
      roll: 0.5
      pitch: 0.2
      yaw: 0.2