fl.hx : front_left_hip_x
fl.hy : front_left_hip_y
fl.kn : front_left_knee
fr.hx : front_right_hip_x
fr.hy : front_right_hip_y
fr.kn : front_right_knee
hl.hx : rear_left_hip_x
hl.hy : rear_left_hip_y
hl.kn : rear_left_knee
hr.hx : rear_right_hip_x
hr.hy : rear_right_hip_y
hr.kn : rear_right_knee
arm0.sh0 : arm0_shoulder_yaw
arm0.sh1 : arm0_shoulder_pitch
arm0.el0 : arm0_elbow_pitch
arm0.el1 : arm0_elbow_roll
arm0.wr0 : arm0_wrist_pitch
arm0.wr1 : arm0_wrist_roll
arm0.f1x : arm0_fingers
