#!/bin/bash

# Create a symbolic link to the spot_description mesh resources
ln -sf $(ros2 pkg prefix --share spot_description)/meshes .

# Create the urdf file from the configured xacro file
xacro $(ros2 pkg prefix --share spot_description)/urdf/spot.urdf.xacro -o urdf/spot.urdf has_arm:=True has_eap:=True

# Update mesh paths
sed -i "s|package://spot_description/||" urdf/spot.urdf

# Remove references to the original file for git reasons
sed -i "/This document was autogenerated by xacro from/d" urdf/spot.urdf