spot_moveit/controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

spot_moveit/joint_state_broadcaster:
  ros__parameters:
    update_rate: 100

spot_moveit/arm_controller:
  ros__parameters:
    joints:
      - arm0_shoulder_yaw
      - arm0_shoulder_pitch
      - arm0_elbow_pitch
      - arm0_elbow_roll
      - arm0_wrist_pitch
      - arm0_wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.0
    update_rate:
      30
