# Default initial positions for spot's ros2_control fake system

initial_positions:
  arm0_elbow_pitch: 0
  arm0_elbow_roll: 0
  arm0_shoulder_pitch: 0
  arm0_shoulder_yaw: 0
  arm0_wrist_pitch: 0
  arm0_wrist_roll: 0