# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm0_shoulder_yaw
      - arm0_shoulder_pitch
      - arm0_elbow_pitch
      - arm0_elbow_roll
      - arm0_wrist_pitch
      - arm0_wrist_roll