sensors:
  - velodyne
  - hand_depth
  - frontleft_depth
  - frontright_depth
  - left_depth
  - right_depth
  - back_depth

velodyne:
  point_cloud_topic: /velodyne_points
  max_range: 4.0
  max_update_rate: 1.0
  padding_offset: 0.15
  padding_scale: 1.4
  point_subsample: 1
  filtered_cloud_topic: spot_moveit_pointcloud
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater

hand_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/hand_rgb/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/hand_rgb/image/filtered_points

frontleft_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/frontleft/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/frontleft/image/filtered_points

frontright_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/frontright/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/frontright/image/filtered_points

left_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/left/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/left/image/filtered_points

right_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/right/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/right/image/filtered_points

back_depth:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /spot_image_server/depth/back/image
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /spot_image_server/depth/back/image/filtered_points
